# External plugins
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
plugins:
  - jekyll-sitemap
  - jekyll-paginate-v2

exclude:
  - "/vendor/"

# Site settings
title: Netdev 0x16
subtitle:
email:
name: 
description: >
  Netdev 0x16 Copyright © 2014-2022 The Netdev Society.

# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
baseurl: /jekyll-sample-netdev.github.io # the subpath of your site, e.g. /blog/
url: https://blog.expertise.dev # the base hostname & protocol for your site
cover: "/assets/header_image.jpg"
logo: "/assets/header_image.jpg"
permalink: none

# Build settings
markdown: kramdown
# inter_post_navigation: false
highlightjs_theme: "monokai-sublime"

# Category descriptions
descriptions:
  - cat: news
    desc: "Netdev News"

  - cat: sessions
    desc: "NetdevConf Sessions"

  # Session types
  - cat: talk
    desc: "session type"

  - cat: tutorial
    desc: "session type"

  - cat: workshop
    desc: "session type"

# Sponsors
# !!!Warning!!!: Please be aware that the order of description will affect the end result. 
#
# - type: platinum | gold | silver | bronze | media
#   url: Sponsor's site URL
#   img: The logo location relative to assets/sponsors folder
#   alt: The logo alt


##### Platinum

# Juniper Networks
sponsors:
  - type: platinum
    url: https://www.juniper.net/
    img: juniper.png
    alt: Juniper Networks logo

  # Google
  - type: platinum
    url: https://opensource.google/
    img: logo_Google_FullColor_1x_722x237px-s.png
    alt: Google Logo

  ##### Gold

  # Google
  - type: gold
    url: https://opensource.google/
    img: google-open-source-vertical-white-text-small.png
    alt: Google Logo

  ##### Silver

  # AMD
  - type: silver
    url: https://www.amd.com
    img: AMD_E_Blk_RGB-s.jpg
    alt: AMD logo

  ##### Bronze

  # Tempesta
  - type: bronze
    url: https://tempesta-tech.com/
    img: tempesta_technologies_logo-s.png
    alt: Tempesta Technologies logo

  # Zevenet
  - type: bronze
    url: https://www.zevenet.com/
    img: Zevenet_Logo_official_bg_white.png
    alt: Zevenet logo

  # Mojatatu
  - type: bronze
    url: http://www.mojatatu.info/mojatatu
    img: mojatatu.png
    alt: Mojatatu Logo

  ##### Media

  # LWN
  - type: media
    url: https://lwn.net/
    img: lwn-s.png
    alt: LWN.net logo
